create schema if not exists private;

create table if not exists public.catalogo_articulos_cambios (
  version bigint generated by default as identity primary key,
  codigo text not null,
  cambios jsonb not null default '{}'::jsonb,
  eliminado boolean not null default false,
  origen text not null,
  created_at timestamptz not null default now()
);

create index if not exists catalogo_articulos_cambios_codigo_version_idx
  on public.catalogo_articulos_cambios (codigo, version);

alter table public.catalogo_articulos_cambios enable row level security;

drop policy if exists catalogo_articulos_cambios_lectura_publica
  on public.catalogo_articulos_cambios;
create policy catalogo_articulos_cambios_lectura_publica
  on public.catalogo_articulos_cambios
  for select
  to anon, authenticated
  using (true);

revoke all on public.catalogo_articulos_cambios from anon, authenticated;
grant select on public.catalogo_articulos_cambios to anon, authenticated;

create or replace function private.catalogo_registrar_cambio_base()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  anterior jsonb := '{}'::jsonb;
  actual jsonb := '{}'::jsonb;
  parche jsonb := '{}'::jsonb;
begin
  if tg_op = 'DELETE' then
    insert into public.catalogo_articulos_cambios (codigo, cambios, eliminado, origen)
    values (old.codigo, jsonb_build_object('activo', false), true, 'catalogo_articulos');
    return old;
  end if;

  actual := jsonb_build_object(
    'codigo_proveedor', new.codigo_proveedor,
    'id_proveedor', new.id_proveedor,
    'nombre', new.nombre,
    'rubro', new.rubro,
    'precio_compra_sin_descuento', new.precio_compra_sin_descuento,
    'precio_compra_con_impuestos', new.precio_compra_con_impuestos,
    'porcentaje_ganancia_min', new.porcentaje_ganancia_min,
    'precio_venta', new.precio_venta,
    'stock', new.stock,
    'stock_progreso', new.stock_progreso,
    'stock_calle5', new.stock_calle5,
    'activo', new.activo
  );

  if tg_op = 'UPDATE' then
    anterior := jsonb_build_object(
      'codigo_proveedor', old.codigo_proveedor,
      'id_proveedor', old.id_proveedor,
      'nombre', old.nombre,
      'rubro', old.rubro,
      'precio_compra_sin_descuento', old.precio_compra_sin_descuento,
      'precio_compra_con_impuestos', old.precio_compra_con_impuestos,
      'porcentaje_ganancia_min', old.porcentaje_ganancia_min,
      'precio_venta', old.precio_venta,
      'stock', old.stock,
      'stock_progreso', old.stock_progreso,
      'stock_calle5', old.stock_calle5,
      'activo', old.activo
    );
  end if;

  select coalesce(jsonb_object_agg(item.key, item.value), '{}'::jsonb)
    into parche
  from jsonb_each(actual) as item
  where (anterior -> item.key) is distinct from item.value;

  if parche <> '{}'::jsonb then
    insert into public.catalogo_articulos_cambios (codigo, cambios, eliminado, origen)
    values (new.codigo, parche, false, 'catalogo_articulos');
  end if;

  return new;
end;
$$;

create or replace function private.catalogo_registrar_cambio_edicion()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  anterior jsonb := '{}'::jsonb;
  actual jsonb := '{}'::jsonb;
  parche jsonb := '{}'::jsonb;
  codigo_articulo text;
begin
  codigo_articulo := case when tg_op = 'DELETE' then old.codigo else new.codigo end;

  if tg_op = 'DELETE' then
    actual := jsonb_build_object(
      'detalle', '', 'tags_ocultos', '[]'::jsonb, 'foto_url', '', 'imagenes', '[]'::jsonb,
      'oferta', false, 'oferta_pct', 0, 'oferta_hasta', null,
      'destacado', false, 'mas_vendido', false, 'acceso_rapido', false,
      'ceramico', false, 'ceramico_m2', 0, 'ceramico_placas', 0,
      'editado_por', null, 'edicion_updated_at', null
    );
  else
    actual := jsonb_build_object(
      'detalle', new.detalle,
      'tags_ocultos', new.tags_ocultos,
      'foto_url', new.foto_url,
      'imagenes', new.imagenes,
      'oferta', new.oferta,
      'oferta_pct', new.oferta_pct,
      'oferta_hasta', new.oferta_hasta,
      'destacado', new.destacado,
      'mas_vendido', new.mas_vendido,
      'acceso_rapido', new.acceso_rapido,
      'ceramico', new.ceramico,
      'ceramico_m2', new.ceramico_m2,
      'ceramico_placas', new.ceramico_placas,
      'editado_por', new.updated_by,
      'edicion_updated_at', new.updated_at
    );
  end if;

  if tg_op = 'UPDATE' or tg_op = 'DELETE' then
    anterior := jsonb_build_object(
      'detalle', old.detalle,
      'tags_ocultos', old.tags_ocultos,
      'foto_url', old.foto_url,
      'imagenes', old.imagenes,
      'oferta', old.oferta,
      'oferta_pct', old.oferta_pct,
      'oferta_hasta', old.oferta_hasta,
      'destacado', old.destacado,
      'mas_vendido', old.mas_vendido,
      'acceso_rapido', old.acceso_rapido,
      'ceramico', old.ceramico,
      'ceramico_m2', old.ceramico_m2,
      'ceramico_placas', old.ceramico_placas,
      'editado_por', old.updated_by,
      'edicion_updated_at', old.updated_at
    );
  end if;

  select coalesce(jsonb_object_agg(item.key, item.value), '{}'::jsonb)
    into parche
  from jsonb_each(actual) as item
  where (anterior -> item.key) is distinct from item.value;

  if parche <> '{}'::jsonb then
    insert into public.catalogo_articulos_cambios (codigo, cambios, eliminado, origen)
    values (codigo_articulo, parche, false, 'catalogo_articulos_edicion');
  end if;

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function private.catalogo_registrar_cambio_base() from public, anon, authenticated;
revoke all on function private.catalogo_registrar_cambio_edicion() from public, anon, authenticated;

drop trigger if exists catalogo_articulos_registrar_cambio on public.catalogo_articulos;
create trigger catalogo_articulos_registrar_cambio
after insert or update or delete on public.catalogo_articulos
for each row execute function private.catalogo_registrar_cambio_base();

drop trigger if exists catalogo_articulos_edicion_registrar_cambio on public.catalogo_articulos_edicion;
create trigger catalogo_articulos_edicion_registrar_cambio
after insert or update or delete on public.catalogo_articulos_edicion
for each row execute function private.catalogo_registrar_cambio_edicion();

alter table public.catalogo_articulos_meta
  add column if not exists patch_version bigint not null default 0;

create or replace function private.catalogo_meta_asignar_patch_version()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  select coalesce(max(c.version), 0)
    into new.patch_version
  from public.catalogo_articulos_cambios c;
  return new;
end;
$$;

revoke all on function private.catalogo_meta_asignar_patch_version() from public, anon, authenticated;

drop trigger if exists catalogo_meta_asignar_patch_version on public.catalogo_articulos_meta;
create trigger catalogo_meta_asignar_patch_version
before insert or update on public.catalogo_articulos_meta
for each row execute function private.catalogo_meta_asignar_patch_version();

update public.catalogo_articulos_meta
set patch_version = 0
where id = 'principal';

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'catalogo_articulos_meta'
  ) then
    alter publication supabase_realtime add table public.catalogo_articulos_meta;
  end if;
end;
$$;
